# Generated by Django 4.0 on 2021-12-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('contact', models.CharField(max_length=12, verbose_name='Contact No')),
                ('password', models.CharField(max_length=12, verbose_name='Password')),
            ],
        ),
    ]
